### ISSUE TITLE
Oddity about commodities

### ISSUE THREAD

**Issue by cintaracorp** [richardthombs/scunpacked#10]
There seem to be lacking values among the commodities. Tram & Meyers at Cellin sell diamonds at 5.85, have a max of 200000 and a very high refresh rate, yet it doesn't show up in scunpacked at all.

**Comment by richardthombs** [comment]
Thanks, this work wasn't supposed to go live, but I pushed it out because there was also a change to show QD spool times I wanted to get out. I'm still trying to get a handle on understanding the shop data and on converting the internal names of shops to the ones we all understand.

**Comment by richardthombs** [comment]
Looking at Gallog, I think it does show up in my data, just with the wrong name:

![image](https://user-images.githubusercontent.com/1511599/76826663-f4910200-6814-11ea-8542-4fb234bb63ca.png)

See the refresh rate per minute? It is the same as indy_miner_001_dust.

![image](https://user-images.githubusercontent.com/1511599/76826880-73863a80-6815-11ea-8bd5-f512413bb388.png)

**Comment by cintaracorp** [comment]
So that would indicate that Tram & Meyers on Cellin is manually chosen to be special. Interesting!

Partly the names seem to follow standard astronomical notation: Star name, planet orbit number counted from the star out, moon orbit letter counted from the closest moon out, but there also seems to be a terminal name as prefix, and outpost name as postfix. You might end up having to do a manual mapping for all names, because it doesn't seem to be consistent.

**Comment by cintaracorp** [comment]
To make a manual mapping of all names, it would be helpful to have a full list of all locations. You might be able to find that from the other meta data sites. Most of the names can then be paired up pretty easily, and the remaining pairings might not be too many to be able to sleuth out like you did with Tram and Meyers.

**Comment by richardthombs** [comment]
Yeah, I have started doing that, but it is a large task. There are translation labels that are slightly helpful - you can get names for Stanton_1 and Stanton_1A - 1st planet and 1st moon of 1st planet etc, but like you say, there is no real consistency in naming to help. I don't know how other sites have solved this problem. Maybe manual too?

**Comment by herokillerJ** [comment]
> 是的，我已经开始这样做了，但这是一项艰巨的任务。有一些翻译标签对您有所帮助-您可以获取Stanton_1和Stanton_1A的名称-第一行星和第一行星的第一颗月亮等，但是就像您说的那样，在命名方面并没有真正的一致性。我不知道其他网站如何解决了这个问题。也许也是手动的？

mapping in Data\localization\english\global.ini

**Comment by herokillerJ** [comment]
> Yeah, I have started doing that, but it is a large task. There are translation labels that are slightly helpful - you can get names for Stanton_1 and Stanton_1A - 1st planet and 1st moon of 1st planet etc, but like you say, there is no real consistency in naming to help. I don't know how other sites have solved this problem. Maybe manual too?

mapping in Data\localization\english\global.ini

**Comment by alistair3149** [comment]
> > Yeah, I have started doing that, but it is a large task. There are translation labels that are slightly helpful - you can get names for Stanton_1 and Stanton_1A - 1st planet and 1st moon of 1st planet etc, but like you say, there is no real consistency in naming to help. I don't know how other sites have solved this problem. Maybe manual too?
> 
> mapping in Data\localization\english\global.ini

There is no consistency in the naming in `global.ini` though. For example, Trams & Myers Mining in the file is `Stanton2a_IndyMine_001`. It is gonna take some manual mapping or maybe regex if there is a pattern to map them.

**Comment by richardthombs** [comment]
Shop names comes from Data\Libs\Subsumption\Shops\ShopLayouts.xml`.

**Comment by EtienneLamoureux** [comment]
One possible connection would be through the star map labels. They are referred to in `Data\Game.xml` and have hierarchy, but I haven't found out how to connect them to the ShopLayouts nor the stantonsystem.xml: it seems like the star map labels "happen" to bring you to the corresponding place when you navigate to them, but it seems disconnected.

**Comment by richardthombs** [comment]
I think the connections are going to have to be done manually. CIG don't need to give the object container names a user-friendly name because we just travel to them rather than seeing them in a listing like we're trying to do in scunpacked.

**Comment by EtienneLamoureux** [comment]
There's always the possibility of computing the closest `global.ini` label for a given shop name in terms of [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance). For the ones that are not too far off, they might reflect the actual names.

**Comment by StiffBiscuit** [comment]
Tram and Myers is not special. They just changed to a more boring convention somewhere along the way, as the number of locations kept increasing. Here's my map so far. I have a few that I haven't mapped so please chime in if you think you know the location.


Decompile   Name | Terminal
-- | --
AdminOffice_Area18 | Area 18 IO North Tower
AdminOffice_Grimhex | Grim Hex Admin Office
AdminOffice_Levski | Levski
AdminOffice_Lorville | Lorville (In L19 Admin Office)
AdminOffice_NewBabbage | New Babbage MT Planetary Services
AdminOffice_PortO | Port Olisar
AdminOffice_Stanton1_L1 | HUR L1
AdminOffice_Stanton1_L2 | HUR L2
AdminOffice_Stanton1_L3 | HUR L3
AdminOffice_Stanton1_L4 | HUR L4
AdminOffice_Stanton1_L5 | HUR L5
AdminOffice_Stanton1_LEO1 | Everus Harbor
AdminOffice_Stanton2_L1 | CRU L1
AdminOffice_Stanton2_L4 | Shallow Fields Station (removed)
AdminOffice_Stanton2_L5 | CRU L5 Admin Office
AdminOffice_Stanton3_L1 | Arc Corp L1
AdminOffice_Stanton3_LEO1 | Baijini Point
AdminOffice_Stanton4_L1 | R & R MIC-L1
AdminOffice_Stanton4_LEO1 | Port Tressler
arccorp_cluster_001_frost | Arc Corp Mining Area 157
arccorp_cluster_001_sand | Arc Corp Mining Area 141
drug_farm_001_frost | Jumptown
DrugLab_Stanton3a_ParadiseCove | Paradise Cove
Fence_Junkyard_Stanton1_1 | Fence Junkyard
Fence_Junkyard_Stanton2b_1 | Brio’s Breaker Yard
Fence_Junkyard_Stanton3b_1 | Samson & Son’s Salvage Center
Fence_RestStop2_4 | Reclamation & Disposal Orinth "Junkyard"
Fence_RestStop2_5 | CRU L5 Locker Room
indy_farmer_001_dust | Gallete Family Farms
indy_farmer_001_sand | Bountiful Harvest Hydroponics
indy_miner_001_dust | Tram & Meyers Mining
indy_miner_001_frost | Benson Mining Outpost
indy_miner_001_sand | Kudre Ore
Klescher_Aberdeen | Klescher Prison Commissary
MiningKiosks_Area18 | Area Refining Terminal
MiningKiosks_GrimHex | Grim Hex Refining Terminal
rayari_cluster_001_dust | Hickes Research Outpost
rayari_cluster_001_frost | Deakins Research Outpost
shubin_cluster_001_sand | Shubin Mining Facility SCD-1
stanton_1_hrst_001 | HDMS Edmond
stanton_1_hrst_002 | HDMS Oparei
stanton_1_hrst_003 | HDMS Pinewood
stanton_1_hrst_004 | HDMS Thedus
stanton_1_hrst_005 | HDMS Hadley
stanton_1_hrst_006 | HDMS Stanhope
stanton_1a_hrst_001 | HDMS Bezdek
stanton_1a_hrst_002 | HDMS Lathan
stanton_1b_hrst_001 | HDMS Norgaard
stanton_1b_hrst_002 | HDMS Anderson
stanton_1c_hrst_001 | HDMS Hahn
stanton_1c_hrst_002 | HMDS Perlman
stanton_1d_hrst_001 | HDMS Woodruff
stanton_1d_hrst_002 | HDMS Ryder
stanton_3a_indy_humboldt | Humbolt Mines
stanton_3a_indy_loveridge | Loveridge Mineral Reserve
stanton_3a_shubin_sal2 | Shubin Mining Facility (SAL 2)
stanton_3a_shubin_sal5 | Shubin Mining Facility (SAL 5)
stanton_3b_arccorp_area045 | Arc Corp mining Area 45
stanton_3b_arccorp_area048 | Arc Corp mining Area 48
stanton_3b_arccorp_area056 | Arc Corp mining Area 56
stanton_3b_arccorp_area061 | Arc Corp mining Area 61
StashHouse_Stanton2a_PrivateProperty | Private Property
StashHouse_Stanton2b_NuenWaste | Nuen Waste Management
StashHouse_Stanton2c_NT999XX | NT-999-XX "Stash house"
StashHouse_Stanton3a_Orphanage | The Orphanage
StashHouse_Stanton4 | Cellin Stash House
t_mills_cluster_001_dust | Terra Mills Hydro Farm
TDD_Area18 | Area 18 TDD Building
TDD_NewBabbage | New Babbage TDD
Transfers_Lorville | Lorville CBD (In Transfers Room)
? | Port Tressler
? | Rayari Deltana Research Outpost
? | Shubin Mining Facility SM0-10
? | Shubin Mining Facility SM0-13
? | Shubin Mining Facility SM0-18
? | Shubin Mining Facility SM0-22

**Comment by richardthombs** [comment]
Thank you very much for this, I wish it could be automated from the data, but I’ve not found a way to do it yet.

When I have some time I’ll turn this into a data file and use it to translate the locations.

Thanks again!

R.
--

**Comment by bovinius** [comment]
Hi guys,

Tressler is system\stanton\stanton4\orbiting\cargodepot_stanton4_leo

>

**Comment by richardthombs** [comment]
I've hardcoded the list @StiffBiscuit gave me into Loader/ShopNames.cs. I don't think the list is complete, patches would be awesome!

I think you're right about the prices drifting away from the hardcoded tick numbers too. I think that happens in game at the moment - the numbers we get from the XML are only used as a starting point when the game servers boot up, I think they vary slowly after then. I expect most of this shop info will become useless once they get the quanta stuff going, but I think that's a year away still from comments I saw the other day.

**Comment by StiffBiscuit** [comment]
I'm stiffbiscuit :). The names are still the same, with some minor tweaks and adds (I can send you the full matchup offline, but please don't publish it). I can tell you that the Excel I built for trading using that list and tick rates, is more accurate than gallog.co. For example gallog says that New Babbage would allow you to unload a full cat of Med Supplies in 1-2 ticks. I can tell you that that's not the case and that the tick rate is much slower.

What's quanta?

Cheers,
-Georgi

________________________________

**Comment by richardthombs** [comment]
Hiya. Don't send me anything I can't include in scunpacked code.

Quanta was a demo at the last citizencon where they showed how they would simulate a dynamic universe with supply and demand.: https://youtu.be/_8VFw1F-olQ
