### ISSUE TITLE
The value of shopBuysThis / shopSellsThis in some commodities does not match

### ISSUE THREAD

**Issue by sergeyvakhramov** [richardthombs/scunpacked#11]
I noticed that for some commodities the values ​​of **shopBuysThis / shopSellsThis** are not correctly indicated. I compared some commodities from **shops.json** with the **ShopLayouts.xml** file. For example, an **Agricium in Port Olisar** should have a **sell** value whereas in json it has a **shopBuysThis value: true**

**Comment by richardthombs** [comment]
Hi there, I just checked out Agricum on [gallog](https://www.gallog.co/commodities/metal/agricium) and it also shows that PO Admin office buys Agricum and doesn't sell it.

**Comment by sergeyvakhramov** [comment]
Compare two files and [see this](https://imgur.com/BOhCjw5)

**Comment by sergeyvakhramov** [comment]
Thank you, I understand what was my mistake

**Comment by richardthombs** [comment]
I have found the words "sell" and "buy" to be _really_ confusing when looking at SC trading :)
