### ISSUE TITLE
Optimize background images

### ISSUE THREAD

**Issue by alistair3149** [richardthombs/scunpacked#21]
The background image used on the site can negatively affect load time when it is not cached (first-time visitor or expired cache). There are several ways that might help to minimize the effect:

- Maintain a collection of background image and serve locally or through a CDN instead of fetching externally. In that way images can be optimized in many ways (screen size, file format, etc.) and ensure that the experience is consistent.
- Add the external sites to preconnect. It is a Band-Aid solution that only requires minimal maintenance, if serving locally and CDN is not an option.

**Comment by richardthombs** [comment]
I think I'll leave it how it is for now. If this issue gets more traction then we can revisit.

**Comment by cintaracorp** [comment]
You might be helped by the <picture> element that lets browsers that understand the element pick an image size they prefer: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture
