### ISSUE TITLE
Missing manufacturer file in Data.p4k

### ISSUE THREAD

**Issue by Mystou** [richardthombs/scunpacked#30]
Hello,

When I try to use the the loader, I got this issue :
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\SCData\unp4k-v3.3.79-master\3.9.0\Data\Libs\Foundry\Records\scitemmanufacturer'.

I don't have the folder scitemmanufacturer in 3.9.0 or 3.9.1.

It's normal?

**Comment by richardthombs** [comment]
What's the path to where you used the unp4k tools to extract the data? That folder should contain a "Data" folder, which is the root of where most of the extracted files go?

You should use that as the path for the --input option in the loader.

**Comment by Mystou** [comment]
The path used was "E:\SCData\unp4k-v3.3.79-master\3.9.0". I've a Data and a Engine folder in it.
The folder Records only have a TagDatabase folder and no "scitemmanufacturer".

There's no "--input" parameter in the README.md for the Loader.exe, only "-scdata" and "-output".

**Comment by richardthombs** [comment]
Sorry, -input is an alias for -scdata

`loader.exe -input "E:\SCData\unp4k-v3.3.79-master\3.9.0" -output <whereever>` should work.

If not, can you tell me what the command line you are using is?

**Comment by richardthombs** [comment]
I just thought - you did do an unforge as well as the two unp4k commands?

**Comment by Mystou** [comment]
I totally missed the unforge step 😓 
I let the tool do his magic and I will close the issue if everything is good.
