### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by pfcapodaca87** [richardthombs/scunpacked#32]
What location is this?  Fence_Junkyard_Stanton1_1

**Comment by EtienneLamoureux** [comment]
It's also defined as `outpostShopNode`. It's location hierarchy is: 
- OOC_Stanton_1_Hurston
  - junksite_a_{70DB91AB-7971-4D00-B3EF-529AC8606465}_socpak
    - ObjectContainer-004
      - buildingWithInterior_b_int_OC
        - outpostShopNode

So nowhere very identifiable from what I can tell.
