### ISSUE TITLE
Add an API call for item listing by type 

### ISSUE THREAD

**Issue by Vyious** [richardthombs/scunpacked#51]
It would be great to get a call that lists all the items in a category in an API call.
e.g. https://scunpacked.com/api/items/powerplants

And that will list all the power plants json file URLs and through that I can just loop through them to get what I want.

**Comment by richardthombs** [comment]
/api/ship-items.json will give you what you need. You'll get ALL the ship components though, which I'm afraid will mean a larger download than you might want.

I'm working on a v2 api which will reduce the size of the download.

Currently I'm trying to avoid server-side API computations to keep my hosting fees lower :)
