### ISSUE TITLE
Transporter categories

### ISSUE THREAD

**Issue by tgmatt** [richardthombs/scunpacked#7]
Freelancer MAX is under the Heavy Freight category, whereas the Caterpillar is under the Medium Freight category. Both are smaller than some of the Hull series of ships, however relative to eachother, the MAX is lesser in every way.

**Comment by richardthombs** [comment]
Sadly that is how CIG have got them classified in the data. I have thought about manually adding corrections, but what I'd really like is to find a way to report the oddities to CIG
