### ISSUE TITLE
Missing file when using loader.exe

### ISSUE THREAD

**Issue by Zetoya** [richardthombs/scunpacked#76]
I'm a bit new in this domain and I tried to parse files from the .p4k.
I've created the loader.exe with .Net and it seems to work fine.
I have extracted all the required files as indicated in the readme with unp4k.exe.

And when i try to use the loader.exe with the command `loader.exe --input=MyInputPath\3.12.0 --output=MyOutputPath\3.12.0-json` it returned an error (I have slightly modified path in the error message for privacy) :

> Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'MyInputPath\Data\Libs\Foundry\Records\entities\scitem'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Loader.EntityService.BuildItemDirectory(String folder) in LoaderPath\EntityService.cs:line 150
   at Loader.EntityService.Initialise(Boolean rebuildCache) in LoaderPath\EntityService.cs:line 87
   at Loader.Program.Main(String[] args) in LoaderPath\Program.cs:line 77

I have checked in the .p4k these folders/files are inexistant and in particular `\data\libs\foundry\records\shipinsurancerecord\shipinsurance.xml`.

So with the update of insurance in 3.12 I asking myself if your code is up to date ? Or if I made a mistake.

Thank you in advance for your help.

**Comment by richardthombs** [comment]
Did you use the unp4k tools? If yes, then try specifying the full path to the input and output folders.

**Comment by Zetoya** [comment]
Hi !

Yes I use the unp4k tools from [https://github.com/dolkensp](url).

And run these 3 commands with the last Data.p4k from Star Citizen 3.12.0 LIVE, build 6742772 as specified in the readme :
`unp4k.exe 'C:\Program Files\Roberts Space Industries\StarCitizen\LIVE\Data.p4k' *.xml`
`unp4k.exe 'C:\Program Files\Roberts Space Industries\StarCitizen\LIVE\Data.p4k' *.ini`
`unforge.exe`

And of course I used the full path for the input and output folder for loader.exe but as mentioned in my previous comment I removed a part of the full path because it contains private information.
But it returned an error for a missing file :
![PrtScr capture_2](https://user-images.githubusercontent.com/76968819/103658266-4608aa00-4f6b-11eb-91b2-db7960b9f5c9.jpg)

And if I checked in these files that the unp4k tools have created the folder `\entities\scitiem` is missing :
![Records](https://user-images.githubusercontent.com/76968819/103658568-ad265e80-4f6b-11eb-90f3-6d07eae1a728.jpg)

And with the unp4k.gui.exe these files are missing to :
![PrtScr capture](https://user-images.githubusercontent.com/76968819/103658675-d0510e00-4f6b-11eb-85a5-95a8418c0d05.jpg)

And I asked to a friend if he found these files in his Data.p4k but not he didn't and we both have a freshly downloaded Data.p4k.

**Comment by LeMyst** [comment]
Do you have space in your input/ouput path? If yes, please use double quote --input="C:\path with space\to\input" --input="C:\path with space\to\output"

**Comment by Zetoya** [comment]
I have no space in my input/output path at all.

I tried anyway because it might have solved the problem. But no, it's still the same problem since the beginning and it's normal, the program can't find files that just don't exist.

And I understand that you may doubt the way I wrote the path but I can assure you the problem is not there at all ! I even tried to create these folder myself to see and the program is progressing well but it still asks for a missing folder at the root of `\data\libs\foundry\records\` until he gets to the moment he needs `\data\libs\foundry\records\shipinsurancerecord\shipinsurance.xml` and that it is suddenly unable to process an empty .xml (which I created from scratch for the test).

**Comment by richardthombs** [comment]
If that file doesn't exist then something isn't right about the game data extracted using the unp4k tools.

Are you sure you did `unforge.exe .` (note the dot as the parameter there).

**Comment by Zetoya** [comment]
I feel so so so dumb...

I didn't see that in the `unforge.exe` command there is a point in paramater.... Three times...

I am very sorry to have disturbed you, thank you for your help and especially for your great work ! 

(It might be good to make a small insert in the readme to emphasize the parameter of this command for people like me who can no longer read).

**Comment by richardthombs** [comment]
lol, I didn't notice it was missing when I read what you'd typed in the first time either :)

**Comment by LeMyst** [comment]
I did the same: https://github.com/richardthombs/scunpacked/issues/30
