### ISSUE TITLE
Mismatched size on ship page compared to component page

### ISSUE THREAD

**Issue by alistair3149** [richardthombs/scunpacked#8]
The size number is mismatched with the actual size of the component.
Take ARGO MPUV for example:
https://scunpacked.com/ships/argo_mpuv

The main engine ARGO_MPUV_Thruster_Main_Fixed and ARGO_MPUV_Thruster_Main_Joint are size 1 thrusters but they are shown as size 4 on the table
https://scunpacked.com/items/argo_mpuv_thruster_main_fixed
https://scunpacked.com/items/argo_mpuv_thruster_main_joint

**Comment by richardthombs** [comment]
This is because the item port which the thruster plugs into is a size 4, but the thruster itself is only a size 1. On the ship table I display the maximum size which can be fitted. I think things like thruster sizes, armour sizes and a few other things have not been sorted out yet by CIG. Eg they have focused on getting the performance values right rather than what size they are.

**Comment by alistair3149** [comment]
Thanks for the answer. I was wondering why the thruster values are all over the places. Btw somehow the non-Warlock Avengers have an EMP hardpoint, are those intended?

**Comment by richardthombs** [comment]
You're welcome. If you want a laugh, check out the Pisces - I think the left main thruster is stronger than the right one. The EMP hard points do exist in the game data, although whether we will ever be able to mount anything there is another matter. I _guess_ that if EMPs were available to purchase, then you might be able to fit one right now, but after looking at the data for about 6 months now, it is pretty obvious that the game data expresses far more options that are actually available and implemented in the game itself.

**Comment by alistair3149** [comment]
Oh I am super entertained with the thruster issues since I am making a component table for all the in-game ships. The thrust values don't match the size of the thruster hardpoints at all lol. And it also annoys me to oblivion with them putting retro thrusters as maneuvering thrusters, while the ship matrix does otherwise :/

**Comment by richardthombs** [comment]
Yeah, it is a bit of a mess at the moment. I imagine that it will get cleaned up if/when we get the opportunity to change these in the loadout ourselves. At the moment, so long as the ship flies OK, I don't think CIG really care about any of the specific values.

**Comment by alistair3149** [comment]
Btw on the Gladius Valiant page, it has a size 3 missile on a size 1 mount which is very weird.

**Comment by richardthombs** [comment]
I don't know where or how scdatabase.com gets its data from, but I take mine straight from the game files and currently this is how the hardpoint_missilerack_right_wing_outer is specified. hardpoint.io agrees with me. I think scdatabase.com is wrong or out of date.

![image](https://user-images.githubusercontent.com/1511599/74735755-3c8a2c80-5249-11ea-9c81-0969c388c374.png)

Again, it makes no sense - a 341 rack should only have size 1 missiles on it, but the game data has the first missile as a size 3 and the remaining ones are size 1.
