### ISSUE TITLE
Use a single style and schema in v2 json keys

### ISSUE THREAD

**Issue by damccull** [richardthombs/scunpacked#80]
In the ships.json file, there is a subsection for each ship called DamageBeforeDetach that looks like this for the AEGS_Avenger_Stalker:
```
"DamageBeforeDetach": {
      "Canopy": 80.0,
      "Wing_Right": 680.0,
      "Wing_Flap_Right": 10.0,
      "WingTip_Right": 20.0,
      "Wing_Left": 680.0,
      "Wing_Flap_Left": 10.0,
      "WingTip_Left": 20.0,
      "HullTail_Right": 20.0,
      "Right_Tail_Fin_Flap": 10.0,
      "HullTail_Left": 20.0,
      "Left_Tail_Fin_Flap": 10.0
    },
```
Only one of these properties follow the same key naming convention as the rest of the file. All the rest are in PascalCase, while these seem to be underscore separated PascalCase. This makes parsing harder, requiring manual renames of these particular fields instead of being able to use a generic renaming scheme. Would you mind renaming these fields to match PascalCase like the others in future versions?

Also, many of the key names need to be normalized. In some ships, the DamageBeforeDestruction's "nose" key is upper case, and in others lower case. This trips up strict parsers. Please normalize these.

**Comment by damccull** [comment]
Additional to the above mentioned problem, many of the key names need to be normalized. In some ships, the DamageBeforeDestruction's "nose" key is upper case, and in others lower case. This trips up strict parsers. Please normalize these.

**Comment by richardthombs** [comment]
You mean for example that `HullTail_Left` should be `Hull_Tail_Left`? Those are names that CIG engineers have assigned the parts, so you'll have to speak to them about that ;)

**Comment by damccull** [comment]
That's what I meant, yes, but apparently, I have the wrong guy :D Lol. Thanks for replying to this even though it's so old.
