### ISSUE TITLE
Loader.exe | Taurus parsing failed

### ISSUE THREAD

**Issue by TheSamon** [richardthombs/scunpacked#85]
Got this exeption since 27/07/2021 PTU patch.
I've temporary workaround it with a 'if (!patchFilename.Contains("RSI_Constellation_Taurus.xml"))' before foreach in VehicleParser.cs at line 67
![image](https://user-images.githubusercontent.com/45072163/127139577-016a7df6-4829-4b2d-a4b2-5b8c929d2b98.png)

**Comment by richardthombs** [comment]
I’ve committed a fix for this now.

R.
--

**Comment by TheSamon** [comment]
Thank you
