### ISSUE TITLE
Loader.exe | AEGS_Redeemer parsing failed

### ISSUE THREAD

**Issue by mortik** [richardthombs/scunpacked#87]
Hey,

i'm getting the following Error when trying to parse data from 3.15.1 PTU

```
EntityService: Cache saved to input folder d:\scdata\3.15.1
Load Localisation
Load Manufacturers
Load Ammunition
Load Insurance
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: AEGS_Redeemer
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Loader.InsuranceLoader.Load() in D:\scdata\scunpacked\Loader\InsuranceLoader.cs:line 22
   at Loader.Program.Main(String[] args) in D:\scdata\scunpacked\Loader\Program.cs:line 112
PS D:\scdata\3.15.1> 
```

**Comment by mortik** [comment]
I put a guard clause in to prevent this error but its actually an issue with the exported xml from the Gamefiles... seems like they put 2 entries in for the Redeemer. Will check if what entry is the one used in the current PTU Patch.

**Comment by jonBarcus** [comment]
Also getting this, but for LIVE 3.15.1.

**Comment by richardthombs** [comment]
Sometimes it takes CIG ages to even notice these kinds of problems. I've added @mortik 's fix so we can work around it.

**Comment by cintaracorp** [comment]
Perhaps we should do some debug output when this happens and notify CIG? We are still all alpha testers and helping CIG with bugs is a part of SC.
