### ISSUE TITLE
Working with the latest unp4k

### ISSUE THREAD

**Issue by pdm-pcb** [richardthombs/scunpacked#89]
Hey there - I'm trying to assemble a local copy of the website's database, and while following the readme instructions, I'm getting a path error. Per EntityServices.cs:82, there's supposed to be a path, "Data\Libs\Foundry\Records\entities". No such path exists after I ran unp4k as documented. Instead I've got TagDatabase and associated file, so loader throws an exception and exits.

Any pointers would be appreciated. =)

**Comment by vrdeals** [comment]
`
cd c:\scdata\3.7.2
unp4k.exe 'C:\Program Files\Roberts Space Industries\StarCitizen\LIVE\Data.p4k' *.xml
unp4k.exe 'C:\Program Files\Roberts Space Industries\StarCitizen\LIVE\Data.p4k' *.ini
unforge.exe .
`

You have surely forgotten the last step
unforge.exe .
Only this process creates all the files in the records folder.

**Comment by pdm-pcb** [comment]
XD! That seems highly likely. I sincerely appreciate the guidance!
