### ISSUE TITLE
json docs

### ISSUE THREAD

**Issue by damccull** [richardthombs/scunpacked#9]
Are there any plans to document the json format you're creating beyond the short description in the bottom of the README.md?

As an aside, I'm digging your project. I was unp4king SC tonight anyways intending to figure out where all the data for ships and items was hidden and having no luck. Your project to the rescue.

**Comment by alistair3149** [comment]
Not the author but the JSON is almost identical to the XML in-game. CIG might change the format of the XML each patch so it'll be a lot of work to maintain a document like that.

**Comment by damccull** [comment]
Really? The json didn't seem at all like the xml to me. I'll look again, though. Thanks for replying!

**Comment by richardthombs** [comment]
The "raw" field is whatever I get from the XML.

**Comment by richardthombs** [comment]
And sorry, I should have answered 26 days ago - Yes, I do plan to document the format, but only the bits that I create. Ie, the "raw" bit that comes directly from CIG's data will probably not be documented, but other fields I add will certainly be documented. Currently I'm just working on the website to help me get a handle on the data and to figure out what custom data I should be putting into the API.

**Comment by damccull** [comment]
Thanks for the response! Your project really makes accessing the data easy, so thanks for building it. I'll close this since you answered. I'm looking forward to some basic docs on your data format once it's stabilized.
