### ISSUE TITLE
Suppressors and Compensators missing from FPS Gear tab

### ISSUE THREAD

**Issue by cintaracorp** [richardthombs/scunpacked#90]
Suppressors and Compensators seem to be missing from the FPS Gear tab. They can be found in the Shops tab, e.g.
`Tacit Suppressor1 (WeaponAttachment) [FPS_Barrel, ballistic_attach, energy_attach]`

**Comment by richardthombs** [comment]
Thanks for the catch, they were classified as ship equipment :/
